.TH updateSupportutils "8" "09 Dec 2010" "updateSupportutils" "Support Utilities Manual"
.SH NAME
updateSupportutils \- Supportutils Auto Update Client
.SH DESCRIPTION
Automatically updates the supportutils and applicable supportutils plugin packages. It can 
be configured for a weekly or monthly cron to keep supportutils current.

.SH FILES
.I /sbin/updateSupportutils
.RS
The Supportutils Auto Update Client
.RE
.SH AUTHOR
Jason Record <jrecord@novell.com>
.SH REPORTING BUGS
Please submit bug fixes, comments or enhancement requests via: 
.B http://code.google.com/p/supportutils-plugin-updater/issues/list
.SH SEE ALSO
.BR supportconfig (8)
.BR supportconfig.conf (5)
