.TH updateSupportutils "8" "10 Dec 2010" "updateSupportutils" "Support Utilities Manual"
.SH NAME
updateSupportutils \- Supportutils Auto Update Client
.SH SYNOPSIS
updateSupportutils [OPTION]
.SH DESCRIPTION
Automatically updates the supportutils and applicable supportutils plugin packages. It can 
be configured for a weekly or monthly cron to keep supportutils current.
.SH OPTIONS
.TP
\fB\-h\fR
The help screen
.TP
\fB\-w\fR
Install a cron for weekly updates
.TP
\fB\-m\fR
Install a cron for monthly updates
.TP
\fB\-d\fR
Delete installed cron entries
.TP
\fB\-l\fR
List cron entries
.TP
\fB\-p\fR
Excludes plugin packages, only updates supportutils and supportutils-plugin-updater
.TP
\fB\-u\fR
Force all applicable supportutils packages to be updated
.TP
\fB\-v\fR
Verbose mode

.SH FILES
.I /sbin/updateSupportutils
.RS
The Supportutils Auto Update Client
.RE
.SH AUTHOR
Jason Record <jrecord@novell.com>
.SH REPORTING BUGS
Please submit bug fixes, comments or enhancement requests via: 
.B http://code.google.com/p/supportutils-plugin-updater/issues/list
.SH SEE ALSO
.BR supportconfig (8)
.BR supportconfig.conf (5)
